/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './Pages/__root.ts'
import { Route as PackagesRouteImport } from './Pages/packages.tsx'
import { Route as IndustriesRouteImport } from './Pages/industries.tsx'
import { Route as DiscoveryRouteImport } from './Pages/discovery.tsx'
import { Route as ContactRouteImport } from './Pages/contact.tsx'
import { Route as ApproachRouteImport } from './Pages/approach.tsx'
import { Route as IndexRouteImport } from './Pages/index'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/discovery': typeof DiscoveryRoute
  '/industries': typeof IndustriesRoute
  '/packages': typeof PackagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/discovery': typeof DiscoveryRoute
  '/industries': typeof IndustriesRoute
  '/packages': typeof PackagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/discovery': typeof DiscoveryRoute
  '/industries': typeof IndustriesRoute
  '/packages': typeof PackagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approach'
    | '/contact'
    | '/discovery'
    | '/industries'
    | '/packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approach'
    | '/contact'
    | '/discovery'
    | '/industries'
    | '/packages'
  id:
    | '__root__'
    | '/'
    | '/approach'
    | '/contact'
    | '/discovery'
    | '/industries'
    | '/packages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  DiscoveryRoute: typeof DiscoveryRoute
  IndustriesRoute: typeof IndustriesRoute
  PackagesRoute: typeof PackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  DiscoveryRoute: DiscoveryRoute,
  IndustriesRoute: IndustriesRoute,
  PackagesRoute: PackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
